config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'

  # resources :cocktails do
  #   resources :doses, only: [:index, :new, :create, :destroy]
  # end
  get 'cocktails/game', to: 'cocktails#game', as: :game

  resources :cocktails, only: [:new, :create, :index, :show, :edit, :destroy] do
    resources :doses, shallow: true
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @cocktails = Cocktail.where("name ILIKE ?", "%#{@name}%")
    end
  end

  def new
    @cocktail = Cocktail.new
  end



  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to @cocktail
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to @cocktail
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def game
    @cocktails = Cocktail.all
    @cocktail = @cocktails.sample
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def index
    @doses = Dose.all
  end

  def show
    @dose = Dose.find(params[:id])
  end

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all.order(name: :desc)
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    @cocktail = @dose.cocktail
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_cocktail.html.erb
<%= Cocktail.all %>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Edit Cocktail!</h1>
  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <p><%= link_to "Back to cocktails", cocktails_path %></p>
</div>

app/views/cocktails/game.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1518895312237-a9e23508077d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1063&q=80);">
  <div class="container">
    <h1>Let the <strong>GAME</strong> begin!</h1>
  </div>
</div>
<!-- <h1><%= @cocktail.name %></h1> -->

<div id="random" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1547059470-3b0c7cd958a4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80)">
  <p>First Round</p>
</div>
<div id="random2" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1556124526-31d95587c657?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80)">
  Second Round
</div>
<div id="random3" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1562016825-b1c7cd4e8deb?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80)">
  Third Round
</div>

<div class="card-category" style="background-color: black" >
  <p><%= link_to "Back to Homepage", cocktails_path %></p>
</div>


<script>
  // const sleep_100 = () => {
  //   await sleep(100);
  // }
  let random = document.querySelector('#random');
  let random2 = document.querySelector('#random2');
  let random3 = document.querySelector('#random3');
  let index = 0;

  // random.addEventListener("click", replaceCocktail('<%= j render 'cocktail' %>'))
  random.addEventListener("click", (e) => {
    let cocktail_name = [];
    for (let i=0; i<50; i++) {
      a1 = "<%= Cocktail.all.sample.name %>"
      a2 = "<%= Cocktail.all.sample.name %>"
      a3 = "<%= Cocktail.all.sample.name %>"
      a4 = "<%= Cocktail.all.sample.name %>"
      a5 = "<%= Cocktail.all.sample.name %>"
      a6 = "<%= Cocktail.all.sample.name %>"
      a7 = "<%= Cocktail.all.sample.name %>"
      a8 = "<%= Cocktail.all.sample.name %>"
      a9 = "<%= Cocktail.all.sample.name %>"
      a10 = "<%= Cocktail.all.sample.name %>"
      a11 = "<%= Cocktail.all.sample.name %>"
      a12 = "<%= Cocktail.all.sample.name %>"
      a13 = "<%= Cocktail.all.sample.name %>"
      a14 = "<%= Cocktail.all.sample.name %>"
      a15 = "<%= Cocktail.all.sample.name %>"
      a16 = "<%= Cocktail.all.sample.name %>"
      a17 = "<%= Cocktail.all.sample.name %>"
      a18 = "<%= Cocktail.all.sample.name %>"
      a19 = "<%= Cocktail.all.sample.name %>"
      a20 = "<%= Cocktail.all.sample.name %>"
      a21 = "<%= Cocktail.all.sample.name %>"
      a22 = "<%= Cocktail.all.sample.name %>"
      cocktail_name.push(a1)
      cocktail_name.push(a2)
      cocktail_name.push(a3)
      cocktail_name.push(a4)
      cocktail_name.push(a5)
      cocktail_name.push(a6)
      cocktail_name.push(a7)
      cocktail_name.push(a8)
      cocktail_name.push(a9)
      cocktail_name.push(a10)
      cocktail_name.push(a11)
      cocktail_name.push(a12)
      cocktail_name.push(a13)
      cocktail_name.push(a14)
      cocktail_name.push(a15)
      cocktail_name.push(a16)
      cocktail_name.push(a17)
      cocktail_name.push(a18)
      cocktail_name.push(a19)
      cocktail_name.push(a20)
      cocktail_name.push(a21)
      cocktail_name.push(a22)
    }

    random.innerHTML = "Drink 1: " + cocktail_name[index];
    random2.innerHTML = "Drink 2: " + cocktail_name[index +100]
    random3.innerHTML = "Drink 3: " +cocktail_name[index +300]
    index++
  })

  // function replaceCocktail(cocktail) {
  //   console.log(this)
  //   this.innerHTML = cocktail
  // }
</script>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1468056961052-15507578a50d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80);">
  <div class="container">
    <h1>WELCOME to your <strong>VIRTUAL BAR</strong>!</h1>
    <!-- <h1>The <strong> BEST </strong> to start your <strong> NIGHTS</strong>!</h1> -->
  </div>
</div>

  <div class="container">
    <h1>The <strong> BEST WAY </strong> to start your <strong> NIGHTS</strong>!</h1>
    <!-- tabs -->

    <ul class="list-inline tabs-underlined">
      <li>
        <a href= <%= game_path %> class="tab-underlined">Drinks</a>
      </li>
      <li>
        <a href= <%= game_path %> class="tab-underlined">Games</a>
      </li>
    </ul>

    <!-- end tabs -->
  </div>
</div>

<!-- search bar -->
<div class="container">
  <%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :name, input_html: {value: ""} %>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>
</div>

<!-- end of the search bar -->

<div class="container">
  <h1>Cocktails</h1>

  <!-- CARD -->
  <div class="row">
    <% @cocktails.each do |c|%>
    <div class=" col-xs-10 col-sm-8 col-md-6 col-lg-3 my-4" style="background-color: rgba(255,255,255,0)">
        <div class="card-product">
          <img src= <%= c.image %> />
          <div class="card-product-infos">
            <h2><%= link_to c.name, cocktail_path(c) %></h2>
            <p><%= link_to "Delete", cocktail_path(c), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<p><%= link_to "Add new Cocktail!", new_cocktail_path, class:"btn btn-primary btn-lg" %></p>

 <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Cocktails Beers Bar Drinks Shots <i class="fas fa-heart"></i> Have fun! 🥳
    </div>
  </div>
</div>

<!-- <div>
  <%= cl_image_tag("hi1qbabexe5squozacat", width: 400, height: 300, crop: :fill) %>
</div> -->

app/views/cocktails/new.html.erb
<div class="container">
  <h1 class="text-center">Add a new Cocktail</h1>
  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, placeholder: "E.g. Mojito", hint: "Bathtub Gin is not a cocktail" %>
  <%= f.submit class:"btn btn-primary" %>
  <% end %>
  <p><%= link_to "Back to cocktails", cocktails_path, class:"avatar"%></p>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <img src= <%= @cocktail.image %> />
  <ul>
    <div>
   <% @cocktail.doses.each do |x| %>
      <div class="card-product-infos">
      <p><%=  x.description %></p>
      <p><%=  x.ingredient.name %></p>
      <p><%= link_to "Delete dose", dose_path(x), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></p>
    </div>
    <% end %>
  </ul>

  <!-- tabs -->
   <!-- <ul class="list-inline tabs-underlined">
      <li>
        <a href="cocktails_path" class="tab-underlined active">Homepage</a>
      </li>
      <li>
        <a href=edit_cocktail_path class="tab-underlined">Edit Cocktail</a>
      </li>
      <li>
        <a href="#" class="tab-underlined">Add new dose</a>
      </li>
    </ul> -->
  <!-- end tabs -->
  <p><%= link_to "Back to cocktails", cocktails_path %></p>
  <p><%= link_to "Edit cocktails", edit_cocktail_path %></p>

  <%= link_to "Add a new dose 😆", new_cocktail_dose_path(@cocktail) %>
  </div>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>
</div>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add a new dose</h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: @ingredients %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <p><%= link_to "Back to cocktails", cocktails_path %></p>
</div>

app/views/doses/view.html.erb
<h1>Doses#view</h1>
<p>Find me in app/views/doses/view.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>